export const mockDataNews: CardWithImageType[] = [
    {
        imageUrl: "/image-holder.png",
        title: "5 xu hướng tóc hot nhất mùa hè 2025",
        date: new Date("2025-05-01"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "Bí quyết giữ màu tóc nhuộm bền đẹp",
        date: new Date("2025-04-20"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "Gội đầu dưỡng sinh – Trải nghiệm thư giãn đỉnh cao",
        date: new Date("2025-04-15"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "Tóc uốn sóng lơi – Sự lựa chọn hoàn hảo cho nàng công sở",
        date: new Date("2025-03-28"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "Chăm sóc tóc hư tổn đúng cách sau khi tẩy",
        date: new Date("2025-03-10"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "5 xu hướng tóc hot nhất mùa hè 2025",
        date: new Date("2025-05-01"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "Bí quyết giữ màu tóc nhuộm bền đẹp",
        date: new Date("2025-04-20"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "Gội đầu dưỡng sinh – Trải nghiệm thư giãn đỉnh cao",
        date: new Date("2025-04-15"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "Tóc uốn sóng lơi – Sự lựa chọn hoàn hảo cho nàng công sở",
        date: new Date("2025-03-28"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "Chăm sóc tóc hư tổn đúng cách sau khi tẩy",
        date: new Date("2025-03-10"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "5 xu hướng tóc hot nhất mùa hè 2025",
        date: new Date("2025-05-01"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "Bí quyết giữ màu tóc nhuộm bền đẹp",
        date: new Date("2025-04-20"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "Gội đầu dưỡng sinh – Trải nghiệm thư giãn đỉnh cao",
        date: new Date("2025-04-15"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "Tóc uốn sóng lơi – Sự lựa chọn hoàn hảo cho nàng công sở",
        date: new Date("2025-03-28"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "Chăm sóc tóc hư tổn đúng cách sau khi tẩy",
        date: new Date("2025-03-10"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "5 xu hướng tóc hot nhất mùa hè 2025",
        date: new Date("2025-05-01"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "Bí quyết giữ màu tóc nhuộm bền đẹp",
        date: new Date("2025-04-20"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "Gội đầu dưỡng sinh – Trải nghiệm thư giãn đỉnh cao",
        date: new Date("2025-04-15"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "Tóc uốn sóng lơi – Sự lựa chọn hoàn hảo cho nàng công sở",
        date: new Date("2025-03-28"),
        status: "Hoạt động",
    },
    {
        imageUrl: "/image-holder.png",
        title: "Chăm sóc tóc hư tổn đúng cách sau khi tẩy",
        date: new Date("2025-03-10"),
        status: "Hoạt động",
    },
];