import { Product } from "@/types/product";

// export const mockDataNews: CardWithImageType[] = [
//     {
//         imageUrl: "/image-holder.png",
//         title: "5 xu hướng tóc hot nhất mùa hè 2025",
//         date: new Date("2025-05-01"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "Bí quyết giữ màu tóc nhuộm bền đẹp",
//         date: new Date("2025-04-20"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "Gội đầu dưỡng sinh – Trải nghiệm thư giãn đỉnh cao",
//         date: new Date("2025-04-15"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "Tóc uốn sóng lơi – Sự lựa chọn hoàn hảo cho nàng công sở",
//         date: new Date("2025-03-28"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "Chăm sóc tóc hư tổn đúng cách sau khi tẩy",
//         date: new Date("2025-03-10"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "5 xu hướng tóc hot nhất mùa hè 2025",
//         date: new Date("2025-05-01"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "Bí quyết giữ màu tóc nhuộm bền đẹp",
//         date: new Date("2025-04-20"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "Gội đầu dưỡng sinh – Trải nghiệm thư giãn đỉnh cao",
//         date: new Date("2025-04-15"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "Tóc uốn sóng lơi – Sự lựa chọn hoàn hảo cho nàng công sở",
//         date: new Date("2025-03-28"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "Chăm sóc tóc hư tổn đúng cách sau khi tẩy",
//         date: new Date("2025-03-10"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "5 xu hướng tóc hot nhất mùa hè 2025",
//         date: new Date("2025-05-01"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "Bí quyết giữ màu tóc nhuộm bền đẹp",
//         date: new Date("2025-04-20"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "Gội đầu dưỡng sinh – Trải nghiệm thư giãn đỉnh cao",
//         date: new Date("2025-04-15"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "Tóc uốn sóng lơi – Sự lựa chọn hoàn hảo cho nàng công sở",
//         date: new Date("2025-03-28"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "Chăm sóc tóc hư tổn đúng cách sau khi tẩy",
//         date: new Date("2025-03-10"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "5 xu hướng tóc hot nhất mùa hè 2025",
//         date: new Date("2025-05-01"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "Bí quyết giữ màu tóc nhuộm bền đẹp",
//         date: new Date("2025-04-20"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "Gội đầu dưỡng sinh – Trải nghiệm thư giãn đỉnh cao",
//         date: new Date("2025-04-15"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "Tóc uốn sóng lơi – Sự lựa chọn hoàn hảo cho nàng công sở",
//         date: new Date("2025-03-28"),
//         status: "Hoạt động",
//     },
//     {
//         imageUrl: "/image-holder.png",
//         title: "Chăm sóc tóc hư tổn đúng cách sau khi tẩy",
//         date: new Date("2025-03-10"),
//         status: "Hoạt động",
//     },
// ];

export const mockDataVideo: CardWithImageType[] = [
    {
        imageUrl: "https://res.cloudinary.com/dijvg89ff/video/upload/v1747836472/caodat/VIDEO%20CHO%20WEB/demo_TVC_HAK_6_tlmcac.mp4",
        status: "Hoạt động",
        date: new Date(Date.now()),
        title: "Sáp vuốt tóc Aurane Pro Formula X Akey",
        slug: "sap-vuot-toc-aurane-pro-formula-x-akey",
    },
    {
        imageUrl: "https://res.cloudinary.com/dijvg89ff/video/upload/v1747836447/caodat/VIDEO%20CHO%20WEB/sa%CC%81p_xanh_mo%CC%9B%CC%81i_zqzgb9.mp4",
        status: "Hoạt động",
        date: new Date(Date.now()),
        title: "Aurane Pro Formula X Akey",
        slug: "aurane-pro-formula-x-akey",
    },
    {
        imageUrl: "https://res.cloudinary.com/dijvg89ff/video/upload/v1747836447/caodat/VIDEO%20CHO%20WEB/tinh_da%CC%82%CC%80u_zb8q8u.mp4",
        status: "Hoạt động",
        date: new Date(Date.now()),
        title: "ZDNB Argan Oil Active Nutri-Reparador",
        slug: "zdnb-argan-oil-active-nutri-reparador",
    },
    {
        imageUrl: "https://res.cloudinary.com/dijvg89ff/video/upload/v1747836446/caodat/VIDEO%20CHO%20WEB/zdnb_rjf2vf.mp4",
        status: "Hoạt động",
        date: new Date(Date.now()),
        title: "Combo ZDNB",
        slug: "combo-zdnb",
    },
    {
        imageUrl: "https://res.cloudinary.com/dijvg89ff/video/upload/v1747836445/caodat/VIDEO%20CHO%20WEB/6315441162045_qn7yay.mp4",
        status: "Hoạt động",
        date: new Date(Date.now()),
        title: "Aurane Pro Formula hồi phục tóc",
        slug: "aurane-pro-formula-hoi-phuc-toc",
    },
    {
        imageUrl: "https://res.cloudinary.com/dijvg89ff/video/upload/v1747836445/caodat/VIDEO%20CHO%20WEB/combo_zndb_ha%CC%82%CC%81p_protein_nrthvw.mp4",
        status: "Hoạt động",
        date: new Date(Date.now()),
        title: "Combo hấp tóc zdnb",
        slug: "combo-hap-toc-zdnb",
    },
    {
        imageUrl: "https://res.cloudinary.com/dijvg89ff/video/upload/v1747836443/caodat/VIDEO%20CHO%20WEB/HAIR_PLEXX_ttefad.mp4",
        status: "Hoạt động",
        date: new Date(Date.now()),
        title: "Hairplexx Caviar",
        slug: "hairplexx-caviar",
    },
    {
        imageUrl: "https://res.cloudinary.com/dijvg89ff/video/upload/v1747836441/caodat/VIDEO%20CHO%20WEB/6444444994094_ailcre.mp4",
        status: "Hoạt động",
        date: new Date(Date.now()),
        title: "Aurane Pro Formula Stylish Wax",
        slug: "aurane-pro-formula-stylish-wax",
    },
    {
        imageUrl: "https://res.cloudinary.com/dijvg89ff/video/upload/v1747836440/caodat/VIDEO%20CHO%20WEB/6444444980137_lwgcqf.mp4",
        status: "Hoạt động",
        date: new Date(Date.now()),
        title: "Aurane Pro Formula Pomade",
        slug: "aurane-pro-formula-pomade",
    },
];

