'use client';
import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/nav-bar";
import Footer from "@/components/footer";
import {Suspense} from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={"w-screen h-full overflow-x-hidden"} lang="en">
    <head>
        {/*<link*/}
        {/*  href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&display=swap"*/}
        {/*  rel="stylesheet"*/}
        {/*/>*/}
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap"
              rel="stylesheet"/>
    </head>
    <body className="antialiased w-screen  ">
    <Suspense fallback={<div>Loading...</div>}>
        <NavBar/>
        <div className={"w-full min-h-screen "}>
                {children}
            </div>
            <Footer/>
        </Suspense>
      </body>
    </html>
  );
}
